//layout files
import "./layout/customHeader.html";
import "./layout/customHomePageTemplate.html";
import "./layout/customHomePage.css";
import "./layout/footer.html";
import "./layout/footer";
import "./layout/layout.less";

//static pages
import "./aboutUs.html";
import "./contact.html";
import "./faq.html";
import "./featuredCloset.html";
import "./rules.html";
import "./static_style.less";
import "./style.html";
import "./terms.html";
import "./works.html";
import "./works";
